language: rust
rust:
  - stable
  - beta
  - nightly
env:
  global:
    - CARGO_MAKE_RUN_CODECOV="true"
script:
  - cargo install --debug cargo-make
  - cargo make ci-flow
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true