[package]
name = "patzar"
version = "0.1.0"
authors = ["samdouble <samleafs@protonmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
regex = "1"

[dev-dependencies]
tarpaulin = "0.18.0-alpha2"
