version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.57.0
    steps:
      - checkout
      - run:
          name: Build and test
          command: |
            export CARGO_MAKE_RUN_CODECOV=true
            cargo install --debug cargo-make
            cargo make ci-flow
