version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.57.0
    steps:
      - checkout
      - run:
          name: Build and test
          command: |
            cargo build
            cargo install cargo-tarpaulin
            cargo tarpaulin -v --fail-under 85
